package com.gameservice.outcome.constant;

public interface ResponseCode {


    int SUCCESS_RESPONSE_CODE = 0;

    int GET_SCORE_BOARD_ERROR_CODE = 7001;

    int CREATE_ROOM_ERROR_CODE = 7002;

    int GET_ROOM_DETAILS_ERROR_CODE = 7003;

    int CREATE_TABLE_ERROR_CODE = 7004;

    int GET_TABLE_DETAILS_ERROR_CODE = 7005;

    int CREATE_GAME_ERROR_CODE = 7006;

    int GET_GAME_DETAILS_ERROR_CODE = 7007;

    int SAVE_PARTICIPANTS_ERROR_CODE = 7008;

    int GET_PARTICIPANTS_DETAILS_ERROR_CODE = 7009;

    int SAVE_DEAL_ERROR_CODE = 7010;

    int GET_DEAL_DETAILS_ERROR_CODE = 7011;

    int START_GAME_ERROR_CODE = 7012;

    int TABLE_OUTCOME_ERROR_CODE = 7013;

    int GET_TURN_DETAILS_ERROR_CODE = 7014;

    int SAVE_TURN_DETAILS_ERROR_CODE = 7015;

    int TABLE_LEAVE_ERROR_CODE = 7016;

    int TABLE_REJOIN_ERROR_CODE = 7017;

    int TABLE_STATUS_ERROR_CODE = 7018;

    int CREATE_TOURNAMENT_ERROR_CODE = 7019;

    int GET_TOURNAMENT_DETAILS_ERROR_CODE = 7020;

    int GET_TOTAL_RAKE_ERROR_CODE = 7021;


}
